[CRIMRE-362] Remove Interests of Justice MAAT property
ministryofjustice/laa-criminal-applications-datastore pull request #129
Opened 2023-07-07 15:30 UTC by mseedat-moj

## Description of change
Removes `interests_of_jusice` from MAAT JSON only, maintains for CrimeApplications, using Schema v1.0.0

## Link to relevant ticket
https://dsdmoj.atlassian.net/browse/CRIMRE-396

## Notes for reviewer / how to test

2023-07-07 15:55 UTC, zheileman commented
There is an extraneous prometheus file floating around...

Also, I would go the other way around, first modify the schemas gem, and then use the new version in datastore, otherwise, once this is merged, there will be a mismatch between what we say in the MAAT schema we return, and what we are returning.

Confirm with MAAT they are ready for this removal.

2023-07-07 15:56 UTC, zheileman requested changes
There is an extraneous prometheus file floating around...

Also, I would go the other way around, first modify the schemas gem, and then use the new version in datastore, otherwise, once this is merged, there will be a mismatch between what we say in the MAAT schema we return, and what we are returning.

Confirm with MAAT they are ready for this removal.

2023-07-07 15:58 UTC, zheileman commented on app/api/datastore/entities/v1/base_application_entity.rb
> -        expose :interests_of_justice
I may feel inclined to leave the base entity untouched and just add to the maat entity:

`unexpose : interests_of_justice`

Feels to me more explicit that way. But functionally would be the same.

2023-07-10 22:47 UTC, mseedat-moj commented
Closed because MAAT team have not yet removed `interests_of_jusice` field from their schema

2023-07-10 22:47 UTC, closed without merging